name: CMake

on:
  push:
    branches: [ "dx11" ]

env:
  BUILD_TYPE: Release

jobs:
  Windows:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Cache Vulkan SDK
      id: cache-vulkan-sdk
      uses: actions/cache@v1
      with:
        path: "C:\\VulkanSDK\\1.2.189.0"
        key: vulkan-sdk-1.2.189.0

    - name: Setup Vulkan
      if: steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.189.0/windows/VulkanSDK-1.2.189.0-Installer.exe" -OutFile VulkanSDK.exe
        $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
        $installer.WaitForExit();
        Copy-Item -Path 'C:\VulkanSDK\1.2.189.0\Include\vulkan' -Destination '${{github.workspace}}\gtaRenderHook' -Recurse

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
